version: "3"
services:
  client:
    build: ./client
    image: mds_provider_client
    container_name: mds_provider_client
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "${PGADMIN_HOST_PORT}:80"
  fake:
    build: ./fake
    image: mds_provider_fake
    container_name: mds_provider_fake
    environment:
      - MDS_BOUNDARY
      - NB_USER
      - NB_UID
      - NB_GID
    ports:
      - "${NB_HOST_PORT}:8888"
    user: root
    volumes:
      - data:/home/${NB_USER}/work/mds/data
  db:
    build: ./db
    image: mds_provider_db
    container_name: mds_provider_db
    depends_on:
      - client
      - server
    environment:
      - POSTGRES_HOSTNAME
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MDS_DB
      - MDS_USER
      - MDS_PASSWORD
  ingest:
    build: ./ingest
    image: mds_provider_ingest
    container_name: mds_provider_ingest
    environment:
      - POSTGRES_HOSTNAME
      - POSTGRES_HOST_PORT
      - MDS_DB
      - MDS_USER
      - MDS_PASSWORD
    ports:
      - "${NB_HOST_PORT}:8888"
    user: root
    volumes:
      - data:/home/${NB_USER}/work/mds/data
  server:
    build: ./server
    image: mds_provider_server
    container_name: mds_provider_server
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

volumes:
  data: